name = "AtlansApi"
uuid = "fe716879-2e18-4081-b090-62ad3424aa7d"
authors = ["Bas Knaake <bas.knaake@deltares.nl>"]
version = "1.0.0-DEV"

[deps]
Atlans = "1fcd1f08-fdb6-477a-a0aa-3f8f0df25597"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
