---
title: "Run AtlansApi locally"
engine: julia
---

`AtlansApi` can be tested on a local machin. Assuming you have the [Julia programming language](https://julialang.org/) installed and the `AtlansApi` repository cloned locally, this can be done by starting an instance of localhost server and using any API testing tool (e.g. Postman). The `AtlansApi` repository contains a script `run_server.jl` which can start a localhost server instance. Start the server by typing the following Powershell command from the repository folder:

```powershell
julia --project "run_server.jl"
```
```
Starting server on http://127.0.0.1:8081
[ Info: Listening on: 127.0.0.1:8081, thread id: 1
```

Now that a server connection has been established and `AtlansApi` is "listening" for incoming requests, you can open a new terminal and start a `Julia` session. The code snippet below can be used as the request to test `AtlansApi`. This uses `AtlansApi.SAMPLE_PAYLOAD` which is the same payload as the [example features](./example.qmd) from the previous page. Running the code 

```julia
using AtlansApi
using HTTP

payload = AtlansApi.SAMPLE_PAYLOAD
url = "http://127.0.0.1:8081/run"
headers = ["Content-Type" => "application/json"]
HTTP.post(url, headers, payload)
```
```
HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
Transfer-Encoding: chunked

{"id":"a1d6aeb4-f9b8-4b9f-be97-91c2e7d917e1","initial":"./docker/output/a1d6aeb4-f9b8-4b9f-be97-91c2e7d917e1/initial.tif","remaining":"./docker/output/a1d6aeb4-f9b8-4b9f-be97-91c2e7d917e1/remaining.tif"}"""
```

Example result of "initial.tif" and "remaining.tif"

<iframe src="../_static/map/example_result.html" width="100%" height="600px" style="border:none;"></iframe>